# Generated by Django 4.2.5 on 2023-10-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbs',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='thumbs'),
        ),
    ]
