# Generated by Django 4.2.5 on 2023-10-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_thumbs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbs',
            new_name='thumbs_up',
        ),
    ]
