# Generated by Django 4.2.5 on 2023-10-10 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_rename_thumbs_post_thumbs_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbs_up_users',
            field=models.ManyToManyField(related_name='thumbs_up_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbs_up',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
