# Generated by Django 4.2.5 on 2023-10-10 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_thumbs_up_users_alter_post_thumbs_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbs_up',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumbs_up_users',
        ),
    ]
